services:
  cache:
    image: redis:7.2.1-alpine
    container_name: bidding-engine-cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxxkKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  cache:
    name: bidding-cache
    driver: local
